### ISSUE TITLE
Production error with lib v1.7.4 on iOS

### ISSUE THREAD

**Issue by rafaelqcosta** [DevCycleHQ/flutter-client-sdk#145] opened 2024-04-26 13:58 UTC
The published build approved by Apple's distribution stopped working. When debugging the same version, we found a new error.
![image](https://github.com/DevCycleHQ/flutter-client-sdk/assets/28444940/dce41d78-1b98-47ec-b8d1-c9e7d63e667a)

Unsupported value: DevCycle.DVCVariableTypes.Number of type __SwiftValue
Is it possible for older versions to stop working? Did any backend change break older builds that use versions prior to 1.7.4?

**Comment by kaushalkapasi** [comment] 2024-04-26 14:08
Hey @rafaelqcosta, we haven't changed anything on our configurations that would result in this issue.

In the screenshot you provided looks like the `sdkKey` was not defined and resulted in a 401 - Unauthorized Error from our backend. In this situation your app would continue to work, however all variables would return default values.

**Comment by rafaelqcosta** [comment] 2024-04-26 14:16
Okay. I'll check if the sdkKey is being passed, but the app shouldn't crash regardless. It's simply closing the application.

**Comment by rafaelqcosta** [comment] 2024-04-26 14:23
This is error by Xcode console:

Unsupported value: DevCycle.DVCVariableTypes.String of type __SwiftValue
*** Assertion failure in void WriteValueOfType(CFTypeRef, CFMutableDataRef, FlutterStandardCodecObjcType, CFTypeRef)(), FlutterStandardCodec.mm:341
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x18df96b28 0x185df2f78 0x18d3fba5c 0x10564cc74 0x10564c8fc 0x18cb04bac 0x18c880ae0 0x18ded011c 0x10564cd88 0x18cb04bac 0x18c880ae0 0x18ded011c 0x10564cd88 0x10564c8fc 0x10564db44 0x105648470 0x1020b07e4 0x1020a9f08 0x1056481a4 0x1050bd768 0x1024c0b98 0x1024c27bc 0x1024d2d58 0x1024d290c 0x18dee151c 0x18dede218 0x18dedd968 0x1d21d34e0 0x190350edc 0x190350518 0x100b90b00 0x1b13fed84)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by rafaelqcosta** [comment] 2024-04-26 14:26
this is my code: 

`Future<void> init(UserEntity? userLogged) async {
    late DevCycleUser user; //= DevCycleUserBuilder().isAnonymous(true).build();

    try {
      if (userLogged != null) {
        user = DevCycleUserBuilder()
            .isAnonymous(false)
            .userId(userLogged.id.toString())
            .email(userLogged.email)
            .name(
              userLogged.name,
            )
            .build();

        final options = DevCycleOptionsBuilder().logLevel(LogLevel.error).build();

        devCycleClient = DevCycleClientBuilder()
            .sdkKey(F().devcycleKey)
            .user(user)
            .options(options)
            .build()
            .onInitialized(([error]) async {
          if (error == null) {
            await getAllVariables();
            changeTheme();
          }
        });
      }
    } catch (e) {
      debugPrint('Erro no devcycle');
    }
  }`

**Comment by rafaelqcosta** [comment] 2024-04-26 14:30
About the sdkKey, it's being set correctly.
![image](https://github.com/DevCycleHQ/flutter-client-sdk/assets/28444940/f2843f96-3255-42ed-aa88-ef783f3342ab)

**Comment by rafaelqcosta** [comment] 2024-04-26 14:39
I was using version 1.7.4, and now I've updated to 1.8.0, but I'm getting the same error.

**Comment by leslie-lau** [comment] 2024-04-26 14:54
@rafaelqcosta thanks for sharing those details, we'll try to reproduce this error on our end and reach out if we have any questions

**Comment by leslie-lau** [comment] 2024-04-26 16:10
Hi @rafaelqcosta, we're able to reproduce the issue and are working on a fix at this time. We'll keep you posted on our progress.

**Comment by igor9silva** [comment] 2024-04-26 16:13
Hi, @rafaelqcosta colleague here. This became a **major** issue for us.

Somehow Apple was able to run, test and approve the app. After distribution it broke. Our app is crashing on start right now.

**Comment by jsalaber** [comment] 2024-04-26 16:35
Hi @rafaelqcosta @igor9silva,

We've identified the issue and we have a pull request open to fix the issue. We'll get it merged and released asap.

**Comment by igor9silva** [comment] 2024-04-27 09:51
Thanks for the follow up @jsalaber, we’ll let you now our results.

**Comment by jsalaber** [comment] 2024-05-10 19:21
Hi @igor9silva we're gonna close this issue out, feel free to open a new one if there's any issues with the new release. Thanks!

**Closed by jsalaber** 2024-05-10 19:21 UTC
